spring:
  application:
    name: spring-hotel-booking
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_app_db
    username: postgres
    password: postgres
    hikari:
      schema: hotel_booking_app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_booking_app_schema
      connection-timeout: 10000
